version: "3.7"
services:
  host:
    image: git.syntro.ch:5500/docker-container/silverstripe:dev
    environment:
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin
      SS_DATABASE_SERVER: database
      SS_DATABASE_NAME: ss_default
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: silverstripe
      SS_ENVIRONMENT_TYPE: dev
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: nfsmount
        target: /var/www/html
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: silverstripe
      MYSQL_DATABASE: ss_default
      MYSQL_USER: silverstripe
      MYSQL_PASSWORD: silverstripe
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: syntro-data
        target: /var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+02:00
volumes:
  syntro-data:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/${PWD}"
